#!/bin/bash

# This script will prepare a Dockerfile

WORK_DIR=$(pwd)

cd ${WORK_DIR}

#Added for security
chmod 700 ${WORK_DIR}/build >/dev/null 2>&1
chmod 700 ${WORK_DIR} >/dev/null 2>&1

source ${WORK_DIR}/.env

cp config/nginx/Dockerfile.build config/nginx/Dockerfile.tmp

if [ "${NGINX_SSL}" = "yes" ]; then
    sed -i 's#__D4D_PEM__#'"ADD ssl/d4d.pem /etc/nginx/ssl/"'#g' config/nginx/Dockerfile.tmp
    sed -i 's#__D4D_KEY_PEM__#'"ADD ssl/d4d-key.pem /etc/nginx/ssl/"'#g' config/nginx/Dockerfile.tmp
else
    sed -i 's#__D4D_PEM__#'""'#g' config/nginx/Dockerfile.tmp
    sed -i 's#__D4D_KEY_PEM__#'""'#g' config/nginx/Dockerfile.tmp
fi

# Remove duplicate
sed -i '$!N; /^\(.*\)\n\1$/!P; D' config/nginx/Dockerfile.tmp

cp config/nginx/Dockerfile.tmp config/nginx/Dockerfile
rm config/nginx/Dockerfile.tmp
