
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - "${PORT_ELASTICSEARCH}:9200"
      - "9300:9300"

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
    depends_on:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    depends_on:
      - elasticsearch
    ports:
      - "${PORT_ELASTICSEARCH_KIBANA}:5601"