
  ngrok:
    image: wernight/ngrok:latest
    ports:
      - ${PORT_NGROK}:${PORT_NGROK}
    links:
      - nginx
    environment:
      - NGROK_LOOK_DOMAIN=${PROJECT_DOMAIN_1}
      - NGROK_PORT=${PORT_WEB}
      - NGROK_AUTH=${NGROK_AUTH}
